### ISSUE TITLE
Add compatibility with voluptuous 0.13.0

### ISSUE THREAD

**Issue by epenet** [ahayworth/python_awair#24]
Could you please adjust the voluptuous requirements?
The current requirement blocks https://github.com/home-assistant/core/pull/68897

**Comment by ahayworth** [comment]
Updated and a new version is published on pypi. Two small notes:

1. Next time, please just send a PR to update the versions rather than asking me to do it. There was no reason inherent to update the versions here ... it's only necessary because of the change you want to make to `home-assistant/core`. It's just kinder to "pitch in" on downstream dependencies rather than asking me to do work that I don't _personally_ need to do.

2. I appreciate how engaged you were on the PR, but if you're going to watch that closely ... send the PR yourself instead. Felt like you were breathing down my neck there a little bit while I was iterating on the test failures. ❤️

**Comment by epenet** [comment]
understood
